# Docker compose file for building docker images and running locally

version: '3.8'

services:
  book_catalog:
    build:
     context: ./book_catalog
     dockerfile: Dockerfile
    ports:
      - "8001:8001"
    environment:
      - DATABASE_URL=postgresql://week7part3_4c4f_user:mMkw4ThDlcLcr1at8Dek0BpbLMwEngfm@dpg-crmlc6dumphs739gj1h0-a.oregon-postgres.render.com/week7part3_4c4f

  inventory_management:
    build:
     context: ./inventory_management
     dockerfile: Dockerfile
    ports:
      - "8002:8002"
    environment:
     - DATABASE_URL=postgresql://week7part3_4c4f_user:mMkw4ThDlcLcr1at8Dek0BpbLMwEngfm@dpg-crmlc6dumphs739gj1h0-a.oregon-postgres.render.com/week7part3_4c4f
